[project]
name = "provider"
version = "0.1.0"
description = "qtcloud-connect FastAPI provider"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.136.1",
    "httpx>=0.28.1",
    "pydantic-settings-vault>=2.1.1",
    "quanttide-connect>=0.1.0",
    "uvicorn>=0.47.0",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

[tool.coverage.run]
source = ["app"]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
]
